### Get all
GET http://localhost:3000/api/products

### Get single
GET http://localhost:3000/api/products/2

### Not found
GET http://localhost:3000/api/products/10

### Create new
POST  http://localhost:3000/api/products
Content-Type: application/json; charset=utf-8

{
    "name": "name",
    "brand": "brand",
    "price": "price",
    "rating": "rating"
}

### Update
PUT  http://localhost:3000/api/products/2
Content-Type: application/json; charset=utf-8

{
   "name": "name",
    "brand": "brand",
    "price": "price",
    "rating": "rating"
}

### Delete
DELETE   http://localhost:3000/api/products/4
Content-Type: application/json; charset=utf-8

